config/routes.rb
Rails.application.routes.draw do

  root to: 'movies#index'


  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :users
  end

  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :reviews

  validates :title,
    presence: true

  validates :director,
    presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validates :description,
    presence: true

  validates :release_date,
    presence: true

  validate :release_date_is_in_the_past

  validate :image_size_validation

  mount_uploader :image, ImageUploader, :mount_on => :image

  def review_average
    reviews.sum(:rating_out_of_ten)/reviews.size if reviews.size >= 1
  end

  scope :duration_search_1, -> { where("runtime_in_minutes < ?", 90) }
  scope :duration_search_2, -> { where("runtime_in_minutes >= ? AND runtime_in_minutes <= ?", 90, 120) }
  scope :duration_search_3, -> { where("runtime_in_minutes > ?", 120) }

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :user,
     presence: true

  validates :movie,
     presence: true

  validates :text,
     presence: true

  validates :rating_out_of_ten,
   numericality: { only_integer: true }
  validates :rating_out_of_ten,
   numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
   numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ApplicationRecord

  has_many :reviews

  has_secure_password

  paginates_per 2

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_check

  def index
    @users = User.all.page params[:page]
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @admin = User.new
  end

  def create
    @admin = User.new(user_params)

    if @admin.save
      session[:user_id] = @admin.id # auto log in
      redirect_to movies_path, notice: "Welcome aboard, #{@admin.firstname}!"
    else
      render :new
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    UserMailer.welcome_email(@user).deliver
    redirect_to admin_users_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  helper_method :current_user

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin_check
    if  current_user.nil? || !current_user.admin
      flash[:alert] = "You must be an Admin to enter."
      redirect_to new_session_path
    end
  end



end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :restrict_access

  def index

    if params
      t = (params[:search] ? "%"+params[:search]+"%" : "%")
      du = (params[:duration] ? params[:duration] : "")
      @movies = Movie.where("title like ? OR director like ?", t, t)

      case du
        when '1' then @movies = @movies.duration_search_1
        when '2' then @movies = @movies.duration_search_2
        when '3' then @movies = @movies.duration_search_3
      end

    else
      @movies = Movie.all.order('created_at DESC')
    end

  end

 def show
   @movie = Movie.find(params[:id])
 end

 def new
   @movie = Movie.new
 end

 def edit
   @movie = Movie.find(params[:id])
 end

 def create
   @movie = Movie.new(movie_params)

   if @movie.save
     redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
   else
     render :new
   end
 end

 def update
   @movie = Movie.find(params[:id])

   if @movie.update_attributes(movie_params)
     redirect_to movie_path(@movie)
   else
     render :edit
   end
 end

   def destroy
     @movie = Movie.find(params[:id])
     @movie.reviews.destroy
     @movie.destroy
     redirect_to movies_path
   end

  protected

  def movie_params
    params.require(:movie).permit(
    :title, :release_date, :director, :runtime_in_minutes,
    :poster_image_url, :description, :image, :remove_image,
    :scale
    )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie
  before_filter :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>edit this member!</h1>
<%= form_for @user, url: edit_admin_user_path(@user)  do |f| %>
 <% if @user.errors.any? %>
   <div>
     <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
     <ul>
       <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
 <div>
   <%= f.label :email %><br>
   <%= f.text_field :email %>
 </div>
 <div>
   <%= f.label :firstname, "First Name" %><br>
   <%= f.text_field :firstname %>
 </div>
 <div>
   <%= f.label :lastname, "Last Name" %><br>
   <%= f.text_field :lastname %>
 </div>
 <div>
   <%= f.label :password %><br>
   <%= f.password_field :password %>
 </div>
 <div>
   <%= f.label :password_confirmation %><br>
   <%= f.password_field :password_confirmation %>
 </div>
 <div class="">
   <%= f.label :are_they_admin? %>
   <%= f.check_box :admin %>
 </div>

 <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/index.html.erb
<h1>All the users!</h1>
<%= link_to "add new users", new_admin_user_path %>
<hr>
<% @users.each do |user| %>
  <h3><%= link_to user.firstname, admin_user_path(user) %></h3>
  <h5><%= user.firstname %> <%= user.lastname %></h5>
    <p><%= user.email %></p>
    <p><%=  %></p>
    <% if user.admin? %>
      <p>Admin</p>
      <% else %>
      <p>
        User
      </p>
      <% end %>
      <hr>
<% end %>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<h1>Add a new member!</h1>
<%= form_for @admin do |f| %>
 <% if @admin.errors.any? %>
   <div>
     <%= pluralize(@admin.errors.count, "error") %> prevented the account from being created:
     <ul>
       <% @admin.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
 <div>
   <%= f.label :email %><br>
   <%= f.text_field :email %>
 </div>
 <div>
   <%= f.label :firstname, "First Name" %><br>
   <%= f.text_field :firstname %>
 </div>
 <div>
   <%= f.label :lastname, "Last Name" %><br>
   <%= f.text_field :lastname %>
 </div>
 <div>
   <%= f.label :password %><br>
   <%= f.password_field :password %>
 </div>
 <div>
   <%= f.label :password_confirmation %><br>
   <%= f.password_field :password_confirmation %>
 </div>
 <div class="">
   <%= f.label :are_they_admin? %>
   <%= f.check_box :admin %>
 </div>

 <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/show.html.erb
<!-- <%= link_to "Back to all movies", movies_path %><br/> -->

<h2><%= @user.firstname %> <%= @user.lastname %> (<%= link_to "edit", edit_admin_user_path(@user) %> | <%= link_to "delete", admin_user_path(@user), method: :delete, data: {confirm: "You sure?"} %>)</h2>
<p><%= @user.email %></p>

<p>
  be the first to review!
</p>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)<br>
      <% if current_user.admin %>
        <%= link_to "Admin Panel", admin_users_path %>
      <% end %>
    <% else %>
       <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RottenMangos</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
     <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
     <%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |key, value| %>
       <%= content_tag(:div, value) %>
     <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <!-- <div>
    <%= f.label :poster_image_url %><br>
    <%= f.text_field :poster_image_url %>
  </div> -->
  <div>
    <%= f.label :Poster_image_upload %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% end %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<% @movies.each do |movie| %>
  <%= link_to image_tag(movie.image), movie_path(movie) %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p>
    <% if movie.review_average %>
      <p><%= movie.review_average %>/10</p>
    <% else %>
      <p>
        <%= link_to "be the first to review!", movie_path(movie) %>
      </p>
    <% end %>
  <hr>
<% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>
<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Submit a movie!", new_movie_path %>
<hr>
<%= form_tag movies_path, :method => "get" do %>
<%= text_field_tag :search, params[:search], placeholder: "Movie Title or Director Name" %>
<%= select_tag :duration, options_for_select([["choose duration", 0], ["Under 90 minutes", 1], ["Between 90 and 120 minutes", 2], ["Over 120 minutes", 3]]) %>
<%= submit_tag "Search" %>
<% end %>
<br>
<hr>

<%= render 'movie' %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.image), movie_path(@movie) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: {confirm: "You sure?"} %>)</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>
<% if @movie.review_average %>
  <p><%= @movie.review_average %>/10</p>
<% else %>
<p>
  be the first to review!
</p>
<% end %>
<hr>
<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<%= link_to "Back to movie", movie_path(@movie) %><br/>
  <h2>Write a review of <em><%= @movie.title %></em>.</h2>

  <%= form_for([@movie, @review]) do |f| %>
   <% if @review.errors.any? %>
     <div>
       <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
       <ul>
         <% @review.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

   <div>
     <%= f.label :text %><br>
     <%= f.text_area "text" %>
   </div>
   <div>
     <%= f.label :rating_out_of_ten %><br>
     <%= f.number_field :rating_out_of_ten %>
   </div>
   <div><%= f.submit "Submit" %></div>
  <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
 <% if @user.errors.any? %>
   <div>
     <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
     <ul>
       <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>
 <div>
   <%= f.label :email %><br>
   <%= f.text_field :email %>
 </div>
 <div>
   <%= f.label :firstname, "First Name" %><br>
   <%= f.text_field :firstname %>
 </div>
 <div>
   <%= f.label :lastname, "Last Name" %><br>
   <%= f.text_field :lastname %>
 </div>
 <div>
   <%= f.label :password %><br>
   <%= f.password_field :password %>
 </div>
 <div>
   <%= f.label :password_confirmation %><br>
   <%= f.password_field :password_confirmation %>
 </div>
 <div><%= f.submit "Submit" %></div>
<% end %>